import { Header } from '@/components/Header'
import 'bootstrap/dist/css/bootstrap.css';
import './globals.css'
import type { Metadata } from 'next'
import { Footer } from '@/components/Footer'


export const metadata: Metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" style={{ height: '100%' }}>
      <body
        className='container'
        style={{ display: 'flex', flexDirection: 'column', height: '100%' }} suppressHydrationWarning={true}>
        <Header />
        <main className='container' style={{ flex: 1 }}>
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  )
}
